SYSTEM:
  PARALLEL: None
MODEL:
  ARCHITECTURE: fpn_3d
  BACKBONE: efficientnet
  BLOCK_TYPE: inverted_res
  BLOCKS: [2, 2, 2, 2, 2]
  FILTERS: [32, 64, 96, 128, 160]
  INPUT_SIZE: [96, 320, 320]
  ISOTROPY: [False, False, True, True, True]
  MIXED_PRECESION: True
  NORM_MODE: gn
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss", "DiceLoss"]]
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  OUT_PLANES: 3
  TARGET_OPT: ["2"]
  PRE_MODEL_ITER: 0
DATASET:
  OUTPUT_PATH: /n/home11/abanerjee/UW_Madison/outs_pytc/Seg_EffNet/
  ENSURE_MIN_SIZE: True
SOLVER:
  LR_SCHEDULER_NAME: OneCycle
  BASE_LR: 0.001
  NAME: "AdamW"
  ITERATION_STEP: 1
  # ITERATION_SAVE: 10000
  ITERATION_TOTAL: 37200  #12400 # 50*248
  SAMPLES_PER_BATCH: 1
  WARMUP_ITERS: 5500
  WEIGHT_DECAY: 0.0008
  ITERATION_SAVE: 1000000
  ITERATION_VAL: 1000000
  ITERATION_RESTART: True
AUGMENTOR:
  ROTATE:
    ROT90: False
  RESCALE:
    ENABLED: True
  SMOOTH: True
  GRAYSCALE:
    ENABLED: False
  FLIP:
    ENABLED: False
  MISSINGSECTION:
    ENABLED: False


